"""
Django settings for tracker project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import environ
import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent.parent
print("Loading local settings from:", os.path.join(BASE_DIR, '.env'))
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7awm!p=&@h44!ur2r-mo1j&8u!k&k!bfd8++%=37zlm@u-$_&7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)
TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = ["*"]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASE_URL = env.bool('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL'),
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'TEST': {
                'NAME': 'test_db.sqlite3',
                },
            }
        }
