# Generated by Django 5.0.6 on 2024-07-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='projects',
            field=models.ManyToManyField(related_name='organizationprojects_set', to='project.project'),
        ),
        migrations.AddField(
            model_name='organization',
            name='repositories',
            field=models.ManyToManyField(related_name='organizationrepositories_set', to='project.gitrepository'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.coreuser'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='deleted',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deletedmodel'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organizationdata'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdata',
            unique_together={('name', 'address_line_1', 'postal_code', 'city', 'state', 'country')},
        ),
    ]
