# Generated by Django 5.2 on 2025-04-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdata',
            name='git_repositories',
            field=models.ManyToManyField(related_name='organizationgitrepositories_set', to='project.gitrepository'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='members',
            field=models.ManyToManyField(related_name='organizationmembers_set', to='core.coreuser'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='projects',
            field=models.ManyToManyField(related_name='organizationprojects_set', to='project.project'),
        ),
        migrations.AddField(
            model_name='organization',
            name='current',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organizationdata'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='core.coreuser'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='deleted',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deletedmodel'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreuser'),
        ),
        migrations.AddField(
            model_name='userlogout',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='core.coreuser'),
        ),
        migrations.AddField(
            model_name='userlogout',
            name='deleted',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deletedmodel'),
        ),
        migrations.AddField(
            model_name='userlogout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreuser'),
        ),
    ]
